### ISSUE TITLE
A new cvpr2021 paper could be added.

### ISSUE THREAD

**Issue by mczhuge** [Eurus-Holmes/Awesome-Multimodal-Research#3]
Kaleido-BERT: Vision-Language Pre-training on Fashion Domain
arxiv: https://arxiv.org/pdf/2103.16110.pdf
code: https://github.com/mczhuge/Kaleido-BERT

**Comment by Eurus-Holmes** [comment]
Thanks for your contribution! Just feel free to raise a PR to this repo.
